import type { WorldDto } from "./world.dto";
import * as Mapper from "./world.mapper";

export type TileType = "ground" | "water" | "mountain" | "field" | "path" | "sand" | "snow";

export interface Tile {
  x: number;         
  y: number;          
  type: TileType;     
}

export interface WorldObject {
  id: string;
  kind: string;
  name: string | null;
  x: number;          
  y: number;
  part: number;
}

export interface World {
  width: number;      
  height: number;     
  tiles: Tile[];
  objects: WorldObject[];
}

const WIDTH = 64;
const HEIGHT = 32;

const tiles: Tile[] = [];

for (let y = 0; y < HEIGHT; y++) {
  for (let x = 0; x < WIDTH; x++) {
    tiles.push({ x, y, type: "ground" });
  }
}

const TILE_OVERRIDES: Array<{ x: number; y: number; type: TileType }> = [
  { x: 9, y: 20, type: "water" },
  { x: 9, y: 21, type: "water" },
  { x: 9, y: 22, type: "water" },
  { x: 9, y: 23, type: "water" },
  { x: 9, y: 24, type: "water" },
  { x: 9, y: 25, type: "water" },
  { x: 9, y: 26, type: "water" },
  { x: 9, y: 27, type: "water" },
  { x: 9, y: 28, type: "water" },
  { x: 9, y: 29, type: "water" },
  { x: 9, y: 30, type: "water" },
  { x: 9, y: 31, type: "water" },
  { x: 8, y: 20, type: "water" },
  { x: 8, y: 21, type: "water" },
  { x: 8, y: 22, type: "water" },
  { x: 8, y: 23, type: "water" },
  { x: 8, y: 24, type: "water" },
  { x: 8, y: 25, type: "water" },
  { x: 8, y: 26, type: "water" },
  { x: 8, y: 27, type: "water" },
  { x: 8, y: 28, type: "water" },
  { x: 8, y: 29, type: "water" },
  { x: 8, y: 30, type: "water" },
  { x: 8, y: 31, type: "water" },
  { x: 7, y: 20, type: "water" },
  { x: 7, y: 21, type: "water" },
  { x: 7, y: 22, type: "water" },
  { x: 7, y: 23, type: "water" },
  { x: 7, y: 24, type: "water" },
  { x: 7, y: 25, type: "water" },
  { x: 7, y: 26, type: "water" },
  { x: 7, y: 27, type: "water" },
  { x: 7, y: 28, type: "water" },
  { x: 7, y: 29, type: "water" },
  { x: 7, y: 30, type: "water" },
  { x: 6, y: 21, type: "water" },
  { x: 6, y: 22, type: "water" },
  { x: 6, y: 23, type: "water" },
  { x: 6, y: 24, type: "water" },
  { x: 6, y: 25, type: "water" },
  { x: 6, y: 26, type: "water" },
  { x: 6, y: 27, type: "water" },
  { x: 6, y: 28, type: "water" },
  { x: 6, y: 29, type: "water" },
  { x: 5, y: 22, type: "water" },
  { x: 5, y: 23, type: "water" },
  { x: 5, y: 24, type: "water" },
  { x: 5, y: 25, type: "water" },
  { x: 5, y: 26, type: "water" },
  { x: 5, y: 27, type: "water" },
  { x: 5, y: 28, type: "water" },
  { x: 4, y: 23, type: "water" },
  { x: 4, y: 24, type: "water" },
  { x: 4, y: 25, type: "water" },
  { x: 4, y: 26, type: "water" },
  { x: 3, y: 24, type: "water" },
  { x: 3, y: 25, type: "water" },
  { x: 10, y: 21, type: "water" },
  { x: 10, y: 22, type: "water" },
  { x: 10, y: 23, type: "water" },
  { x: 10, y: 24, type: "water" },
  { x: 10, y: 25, type: "water" },
  { x: 10, y: 26, type: "water" },
  { x: 10, y: 27, type: "water" },
  { x: 10, y: 28, type: "water" },
  { x: 10, y: 29, type: "water" },
  { x: 10, y: 30, type: "water" },
  { x: 11, y: 22, type: "water" },
  { x: 11, y: 23, type: "water" },
  { x: 11, y: 24, type: "water" },
  { x: 11, y: 25, type: "water" },
  { x: 11, y: 26, type: "water" },
  { x: 11, y: 27, type: "water" },
  { x: 11, y: 28, type: "water" },
  { x: 11, y: 29, type: "water" },
  { x: 12, y: 22, type: "water" },
  { x: 12, y: 23, type: "water" },
  { x: 12, y: 24, type: "water" },
  { x: 12, y: 25, type: "water" },
  { x: 12, y: 26, type: "water" },
  { x: 12, y: 27, type: "water" },
  { x: 12, y: 28, type: "water" },
  { x: 12, y: 29, type: "water" },
  { x: 13, y: 23, type: "water" },
  { x: 13, y: 24, type: "water" },
  { x: 13, y: 25, type: "water" },
  { x: 13, y: 26, type: "water" },
  { x: 13, y: 27, type: "water" },
  { x: 13, y: 28, type: "water" },
  { x: 14, y: 23, type: "water" },
  { x: 14, y: 24, type: "water" },
  { x: 14, y: 25, type: "water" },
  { x: 14, y: 26, type: "water" },
  { x: 14, y: 27, type: "water" },
  { x: 15, y: 24, type: "water" },
  { x: 15, y: 25, type: "water" },
  { x: 15, y: 26, type: "water" },
  { x: 16, y: 24, type: "water" },
  { x: 16, y: 25, type: "water" },
  { x: 17, y: 24, type: "water" },
  { x: 17, y: 25, type: "water" },
  { x: 18, y: 24, type: "water" },
  { x: 18, y: 23, type: "water" },
  { x: 18, y: 22, type: "water" },
  { x: 19, y: 22, type: "water" },
  { x: 20, y: 22, type: "water" },
  { x: 21, y: 22, type: "water" },
  { x: 22, y: 22, type: "water" },
  { x: 23, y: 22, type: "water" },
  { x: 24, y: 22, type: "water" },
  { x: 25, y: 22, type: "water" },
  { x: 26, y: 21, type: "water" },
  { x: 26, y: 22, type: "water" },
  { x: 26, y: 23, type: "water" },
  { x: 27, y: 20, type: "water" },
  { x: 27, y: 21, type: "water" },
  { x: 27, y: 22, type: "water" },
  { x: 27, y: 23, type: "water" },
  { x: 27, y: 24, type: "water" },
  { x: 28, y: 19, type: "water" },
  { x: 28, y: 20, type: "water" },
  { x: 28, y: 21, type: "water" },
  { x: 28, y: 22, type: "water" },
  { x: 28, y: 23, type: "water" },
  { x: 28, y: 24, type: "water" },
  { x: 28, y: 25, type: "water" },
  { x: 29, y: 20, type: "water" },
  { x: 29, y: 21, type: "water" },
  { x: 29, y: 22, type: "water" },
  { x: 29, y: 23, type: "water" },
  { x: 29, y: 24, type: "water" },
  { x: 30, y: 21, type: "water" },
  { x: 30, y: 22, type: "water" },
  { x: 30, y: 23, type: "water" },
  { x: 31, y: 22, type: "water" },
  { x: 32, y: 22, type: "water" },
  { x: 33, y: 22, type: "water" },
  { x: 34, y: 22, type: "water" },
  { x: 34, y: 21, type: "water" },
  { x: 34, y: 20, type: "water" },
  { x: 34, y: 19, type: "water" },
  { x: 34, y: 18, type: "water" },
  { x: 34, y: 17, type: "water" },
  { x: 34, y: 16, type: "water" },
  { x: 34, y: 15, type: "water" },
  { x: 34, y: 14, type: "water" },
  { x: 34, y: 13, type: "water" },
  { x: 34, y: 12, type: "water" },
  { x: 35, y: 12, type: "water" },
  { x: 36, y: 12, type: "water" },
  { x: 36, y: 11, type: "water" },
  { x: 36, y: 11, type: "water" },
  { x: 36, y: 10, type: "water" },
  { x: 36, y: 9, type: "water" },
  { x: 36, y: 8, type: "water" },
  { x: 37, y: 8, type: "water" },
  { x: 38, y: 8, type: "water" },
  { x: 39, y: 8, type: "water" },
  { x: 39, y: 7, type: "water" },
  { x: 39, y: 6, type: "water" },
  { x: 39, y: 5, type: "water" },
  { x: 40, y: 5, type: "water" },
  { x: 41, y: 5, type: "water" },
  { x: 41, y: 4, type: "water" },
  { x: 42, y: 4, type: "water" },
  { x: 43, y: 4, type: "water" },
  { x: 44, y: 4, type: "water" },
  { x: 44, y: 3, type: "water" },
  { x: 45, y: 3, type: "water" },
  { x: 46, y: 3, type: "water" },
  { x: 47, y: 3, type: "water" },
  { x: 48, y: 3, type: "water" },
  { x: 49, y: 2, type: "water" },
  { x: 49, y: 3, type: "water" },
  { x: 35, y: 21, type: "water" },
  { x: 36, y: 21, type: "water" },
  { x: 36, y: 22, type: "water" },
  { x: 37, y: 22, type: "water" },
  { x: 38, y: 22, type: "water" },
  { x: 39, y: 22, type: "water" },
  { x: 40, y: 22, type: "water" },
  { x: 41, y: 22, type: "water" },
  { x: 42, y: 22, type: "water" },
  { x: 43, y: 22, type: "water" },
  { x: 44, y: 22, type: "water" },
  { x: 45, y: 22, type: "water" },
  { x: 46, y: 22, type: "water" },
  { x: 46, y: 23, type: "water" },
  { x: 47, y: 23, type: "water" },
  { x: 48, y: 23, type: "water" },
  { x: 49, y: 23, type: "water" },
  { x: 50, y: 23, type: "water" },
  { x: 50, y: 22, type: "water" },
  { x: 50, y: 21, type: "water" },
  { x: 50, y: 20, type: "water" },
  { x: 50, y: 19, type: "water" },
  { x: 50, y: 18, type: "water" },
  { x: 50, y: 17, type: "water" },
  { x: 50, y: 16, type: "water" },
  { x: 49, y: 16, type: "water" },
  { x: 49, y: 15, type: "water" },
  { x: 49, y: 14, type: "water" },
  { x: 49, y: 13, type: "water" },
  { x: 49, y: 12, type: "water" },
  { x: 49, y: 11, type: "water" },
  { x: 49, y: 10, type: "water" },
  { x: 50, y: 10, type: "water" },
  { x: 50, y: 9, type: "water" },
  { x: 50, y: 8, type: "water" },
  { x: 50, y: 7, type: "water" },
  { x: 51, y: 7, type: "water" },
  { x: 51, y: 6, type: "water" },
  { x: 51, y: 5, type: "water" },
  { x: 51, y: 4, type: "water" },
  { x: 51, y: 3, type: "water" },
  { x: 50, y: 3, type: "water" },
  { x: 50, y: 2, type: "water" },
  { x: 50, y: 1, type: "water" },
  { x: 50, y: 0, type: "water" },

  { x: 4, y: 0, type: "snow" },
  { x: 6, y: 0, type: "snow" },
  { x: 7, y: 0, type: "snow" },
  { x: 9, y: 0, type: "snow" },
  { x: 8, y: 1, type: "snow" },
  { x: 9, y: 1, type: "snow" },
  { x: 9, y: 2, type: "snow" },
  { x: 10, y: 0, type: "snow" },
  { x: 11, y: 0, type: "snow" },
  { x: 11, y: 3, type: "snow" },
  { x: 12, y: 0, type: "snow" },
  { x: 13, y: 0, type: "snow" },
  { x: 14, y: 0, type: "snow" },
  { x: 15, y: 0, type: "snow" },
  { x: 16, y: 0, type: "snow" },
  { x: 17, y: 0, type: "snow" },
  { x: 18, y: 0, type: "snow" },
  { x: 19, y: 0, type: "snow" },
  { x: 20, y: 0, type: "snow" },
  { x: 21, y: 0, type: "snow" },
  { x: 22, y: 0, type: "snow" },
  { x: 23, y: 0, type: "snow" },
  { x: 24, y: 0, type: "snow" },
  { x: 25, y: 0, type: "snow" },
  { x: 26, y: 0, type: "snow" },
  { x: 11, y: 0, type: "snow" },
  { x: 12, y: 0, type: "snow" },
  { x: 13, y: 0, type: "snow" },
  { x: 10, y: 1, type: "snow" },
  { x: 12, y: 1, type: "snow" },
  { x: 13, y: 1, type: "snow" },
  { x: 15, y: 1, type: "snow" },
  { x: 16, y: 1, type: "snow" },
  { x: 17, y: 1, type: "snow" },
  { x: 18, y: 1, type: "snow" },
  { x: 19, y: 1, type: "snow" },
  { x: 21, y: 1, type: "snow" },
  { x: 22, y: 1, type: "snow" },
  { x: 24, y: 1, type: "snow" },
  { x: 25, y: 1, type: "snow" },
  { x: 11, y: 1, type: "snow" },
  { x: 13, y: 1, type: "snow" },
  { x: 12, y: 2, type: "snow" },
  { x: 13, y: 2, type: "snow" },
  { x: 14, y: 2, type: "snow" },
  { x: 15, y: 2, type: "snow" },
  { x: 17, y: 2, type: "snow" },
  { x: 18, y: 2, type: "snow" },
  { x: 19, y: 2, type: "snow" },
  { x: 21, y: 2, type: "snow" },
  { x: 22, y: 2, type: "snow" },
  { x: 13, y: 3, type: "snow" },
  { x: 15, y: 3, type: "snow" },
  { x: 20, y: 3, type: "snow" },

  { x: 22, y: 25, type: "path" },
  { x: 22, y: 24, type: "path" },
  { x: 22, y: 23, type: "path" },
  { x: 22, y: 21, type: "path" },
  { x: 22, y: 20, type: "path" },
  { x: 22, y: 19, type: "path" },
  { x: 22, y: 18, type: "path" },
  { x: 22, y: 17, type: "path" },
  { x: 22, y: 16, type: "path" },
  { x: 22, y: 15, type: "path" },
  { x: 22, y: 14, type: "path" },
  { x: 22, y: 13, type: "path" },
  { x: 22, y: 12, type: "path" },
  { x: 22, y: 11, type: "path" },
  { x: 21, y: 11, type: "path" },
  { x: 20, y: 11, type: "path" },
  { x: 20, y: 10, type: "path" },
  { x: 19, y: 10, type: "path" },
  { x: 18, y: 10, type: "path" },
  { x: 18, y: 11, type: "path" },
  { x: 17, y: 11, type: "path" },
  { x: 16, y: 11, type: "path" },
  { x: 15, y: 11, type: "path" },
  { x: 14, y: 11, type: "path" },
  { x: 13, y: 11, type: "path" },
  { x: 12, y: 11, type: "path" },
  { x: 11, y: 11, type: "path" },
  { x: 10, y: 11, type: "path" },
  { x: 9, y: 11, type: "path" },
  { x: 8, y: 11, type: "path" },
  { x: 7, y: 11, type: "path" },
  { x: 6, y: 11, type: "path" },
  { x: 5, y: 11, type: "path" },
  { x: 4, y: 11, type: "path" },
  { x: 4, y: 10, type: "path" },
  { x: 18, y: 9, type: "path" },
  { x: 18, y: 8, type: "path" },
  { x: 18, y: 7, type: "path" },
  { x: 17, y: 7, type: "path" },
  { x: 17, y: 6, type: "path" },
  { x: 17, y: 5, type: "path" },
  { x: 17, y: 4, type: "path" },
  { x: 17, y: 3, type: "path" },
  { x: 23, y: 13, type: "path" },
  { x: 24, y: 13, type: "path" },
  { x: 25, y: 13, type: "path" },
  { x: 26, y: 13, type: "path" },
  { x: 27, y: 13, type: "path" },
  { x: 28, y: 13, type: "path" },
  { x: 29, y: 13, type: "path" },
  { x: 30, y: 13, type: "path" },
  { x: 31, y: 13, type: "path" },
  { x: 32, y: 13, type: "path" },
  { x: 32, y: 14, type: "path" },
  { x: 33, y: 14, type: "path" },
  { x: 35, y: 14, type: "path" },
  { x: 35, y: 13, type: "path" },
  { x: 36, y: 13, type: "path" },
  { x: 37, y: 13, type: "path" },
  { x: 38, y: 13, type: "path" },
  { x: 39, y: 13, type: "path" },
  { x: 40, y: 13, type: "path" },

  { x: 11, y: 31, type: "sand"},
  { x: 12, y: 31, type: "sand"},
  { x: 14, y: 31, type: "sand"},
  { x: 15, y: 31, type: "sand"},
  { x: 12, y: 30, type: "sand"},
  { x: 13, y: 30, type: "sand"},
  { x: 14, y: 30, type: "sand"},
  { x: 15, y: 30, type: "sand"},
  { x: 16, y: 30, type: "sand"},
  { x: 13, y: 29, type: "sand"},
  { x: 14, y: 29, type: "sand"},
  { x: 16, y: 29, type: "sand"},
  { x: 16, y: 26, type: "sand"},
  { x: 17, y: 26, type: "sand"},
  { x: 18, y: 26, type: "sand"},
  { x: 18, y: 25, type: "sand"},
  { x: 19, y: 24, type: "sand"},
  { x: 20, y: 26, type: "sand"},
  { x: 21, y: 23, type: "sand"},
  { x: 23, y: 23, type: "sand"},
  { x: 15, y: 27, type: "sand"},
  { x: 15, y: 28, type: "sand"},
  { x: 15, y: 29, type: "sand"},
  { x: 16, y: 27, type: "sand"},
  { x: 16, y: 28, type: "sand"},
  { x: 16, y: 29, type: "sand"},
  { x: 16, y: 30, type: "sand"},
  { x: 17, y: 27, type: "sand"},
  { x: 17, y: 28, type: "sand"},
  { x: 17, y: 29, type: "sand"},
  { x: 17, y: 30, type: "sand"},
  { x: 17, y: 31, type: "sand"},
  { x: 18, y: 28, type: "sand"},
  { x: 18, y: 30, type: "sand"},
  { x: 19, y: 27, type: "sand"},
  { x: 19, y: 28, type: "sand"},
  { x: 19, y: 29, type: "sand"},
  { x: 19, y: 30, type: "sand"},
  { x: 19, y: 31, type: "sand"},
  { x: 20, y: 27, type: "sand"},
  { x: 20, y: 28, type: "sand"},
  { x: 20, y: 30, type: "sand"},
  { x: 20, y: 31, type: "sand"},
  { x: 21, y: 27, type: "sand"},
  { x: 21, y: 28, type: "sand"},
  { x: 21, y: 29, type: "sand"},
  { x: 21, y: 31, type: "sand"},
  { x: 22, y: 27, type: "sand"},
  { x: 22, y: 28, type: "sand"},
  { x: 22, y: 30, type: "sand"},
  { x: 22, y: 31, type: "sand"},
  { x: 23, y: 27, type: "sand"},
  { x: 23, y: 28, type: "sand"},
  { x: 23, y: 30, type: "sand"},
  { x: 23, y: 31, type: "sand"},
  { x: 24, y: 26, type: "sand"},
  { x: 24, y: 27, type: "sand"},
  { x: 24, y: 28, type: "sand"},
  { x: 24, y: 29, type: "sand"},
  { x: 24, y: 30, type: "sand"},
  { x: 25, y: 25, type: "sand"},
  { x: 25, y: 28, type: "sand"},
  { x: 25, y: 29, type: "sand"},
  { x: 25, y: 31, type: "sand"},
  { x: 26, y: 25, type: "sand"},
  { x: 26, y: 27, type: "sand"},
  { x: 26, y: 26, type: "sand"},
  { x: 26, y: 27, type: "sand"},
  { x: 26, y: 29, type: "sand"},
  { x: 26, y: 30, type: "sand"},
  { x: 26, y: 31, type: "sand"},
  { x: 27, y: 26, type: "sand"},
  { x: 27, y: 27, type: "sand"},
  { x: 27, y: 28, type: "sand"},
  { x: 27, y: 29, type: "sand"},
  { x: 27, y: 30, type: "sand"},
  { x: 27, y: 31, type: "sand"},
  { x: 28, y: 27, type: "sand"},
  { x: 28, y: 28, type: "sand"},
  { x: 28, y: 29, type: "sand"},
  { x: 28, y: 30, type: "sand"},
  { x: 29, y: 28, type: "sand"},
  { x: 29, y: 29, type: "sand"},
  { x: 30, y: 28, type: "sand"},
  { x: 30, y: 29, type: "sand"},
  { x: 30, y: 30, type: "sand"},
  { x: 30, y: 31, type: "sand"},
  { x: 31, y: 29, type: "sand"},
  { x: 31, y: 30, type: "sand"},
  { x: 31, y: 31, type: "sand"},
  { x: 32, y: 31, type: "sand"},
  { x: 20, y: 23, type: "sand"},
  { x: 19, y: 24, type: "sand"},
  { x: 24, y: 23, type: "sand"},
  { x: 25, y: 23, type: "sand"},
  { x: 25, y: 24, type: "sand"},

  
];

export const mockWorldDto: WorldDto = {
  globals: {
    cell_resolution: { x: WIDTH, y: HEIGHT },
  },
  entities: [
    {
      id: "Settlement_Rockdale",
      category: "Settlement",
      metadata: { name: "Rockdale" },
      cells: [
        { x: 4, y: 8, prop: { name: "city", part: 0 } },
        { x: 4, y: 9, prop: { name: "city", part: 3 } },
        { x: 3, y: 8, prop: { name: "city", part: 2 } },
        { x: 3, y: 9, prop: { name: "city", part: 1 } },
        { x: 5, y: 9, prop: { name: "city", part: 5 } },

        { x: 8, y: 3, prop: { name: "tree_birch", part: 1 } },
        { x: 5, y: 3, prop: { name: "tree_birch", part: 1 } },
        { x: 2, y: 5, prop: { name: "tree_birch", part: 0 } },
        { x: 4, y: 7, prop: { name: "tree_birch", part: 0 } },
        { x: 0, y: 9, prop: { name: "tree_birch", part: 0 } },
        { x: 7, y: 6, prop: { name: "tree_birch", part: 0 } },
        { x: 8, y: 7, prop: { name: "tree_birch", part: 0 } },
        { x: 7, y: 12, prop: { name: "tree_birch", part: 0 } },
        { x: 8, y: 13, prop: { name: "tree_birch", part: 0 } },
        { x: 2, y: 11, prop: { name: "tree_birch", part: 0 } },
        { x: 2, y: 3, prop: { name: "tree_maple", part: 1 } },
        { x: 8, y: 4, prop: { name: "tree_maple", part: 0 } },
        { x: 4, y: 5, prop: { name: "tree_maple", part: 0 } },
        { x: 5, y: 13, prop: { name: "tree_maple", part: 0 } },
        { x: 0, y: 11, prop: { name: "tree_maple", part: 0 } },
        { x: 12, y: 6, prop: { name: "tree_maple", part: 0 } },
        { x: 4, y: 1, prop: { name: "tree_pine", part: 1 } },
        { x: 0, y: 7, prop: { name: "tree_pine", part: 0 } },
        { x: 3, y: 6, prop: { name: "tree_pine", part: 0 } },
        { x: 1, y: 12, prop: { name: "tree_pine", part: 0 } },
      ],
    },

    {
      id: "Settlement_Highcrest",
      category: "Settlement",
      metadata: { name: "Highcrest" },
      cells: [
        { x: 17, y: 1, prop: { name: "city", part: 2 } },
        { x: 17, y: 2, prop: { name: "city", part: 3 } },
        
        // small forest around Highcrest
        { x: 15, y: 2, prop: { name: "tree_pine", part: 1 } },
        { x: 21, y: 0, prop: { name: "tree_pine", part: 1 } },
        { x: 15, y: 0, prop: { name: "tree_pine", part: 1 } },
        { x: 16, y: 1, prop: { name: "tree_pine", part: 1 } },
        { x: 21, y: 2, prop: { name: "tree_pine", part: 1 } },
        { x: 9, y: 0, prop: { name: "tree_pine", part: 1 } },
        { x: 20, y: 1, prop: { name: "tree_oak", part: 1 } },
        { x: 18, y: 2, prop: { name: "tree_oak", part: 1 } },
        { x: 13, y: 0, prop: { name: "tree_oak", part: 1 } },
        { x: 12, y: 1, prop: { name: "tree_maple", part: 1 } },
        { x: 19, y: 1, prop: { name: "tree_maple", part: 1 } },
        { x: 24, y: 0, prop: { name: "tree_maple", part: 1 } },
        { x: 25, y: 1, prop: { name: "tree_birch", part: 1 } },
        { x: 19, y: 0, prop: { name: "tree_birch", part: 1 } },

        { x: 4, y: 0, prop: { name: "rock", part: 1 } },
        { x: 6, y: 0, prop: { name: "rock", part: 0 } },
        { x: 7, y: 0, prop: { name: "rock", part: 0 } },
        { x: 7, y: 1, prop: { name: "rock", part: 1 } },
        { x: 8, y: 1, prop: { name: "rock", part: 1 } },
        { x: 9, y: 1, prop: { name: "rock", part: 0 } },
        { x: 9, y: 2, prop: { name: "rock", part: 1 } },
        { x: 10, y: 2, prop: { name: "rock", part: 0 } },
        { x: 10, y: 2, prop: { name: "rock", part: 1 } },
        { x: 10, y: 3, prop: { name: "rock", part: 0 } },
        { x: 11, y: 3, prop: { name: "rock", part: 0 } },
        { x: 12, y: 3, prop: { name: "rock", part: 0 } },
        { x: 13, y: 2, prop: { name: "rock", part: 0 } },
        { x: 14, y: 2, prop: { name: "rock", part: 1 } },
        { x: 15, y: 3, prop: { name: "rock", part: 0 } },
        { x: 14, y: 5, prop: { name: "rock", part: 0 } },
        { x: 13, y: 6, prop: { name: "rock", part: 0 } },
        { x: 13, y: 7, prop: { name: "rock", part: 0 } },
        { x: 14, y: 7, prop: { name: "rock", part: 0 } },
        { x: 12, y: 8, prop: { name: "rock", part: 0 } },
        { x: 12, y: 9, prop: { name: "rock", part: 0 } },
        { x: 11, y: 9, prop: { name: "rock", part: 0 } },
        { x: 10, y: 9, prop: { name: "rock", part: 0 } },
        { x: 0, y: 12, prop: { name: "rock", part: 0 } },
        { x: 1, y: 13, prop: { name: "rock", part: 0 } },
        { x: 2, y: 13, prop: { name: "rock", part: 0 } },
        { x: 3, y: 12, prop: { name: "rock", part: 0 } },
      ],
    },

    {
      id: "Settlement_Riverfall",
      category: "Settlement",
      metadata: { name: "Riverfall" },
      cells: [
        { x: 40, y: 11, prop: { name: "city", part: 0 } },
        { x: 40, y: 12, prop: { name: "city", part: 3 } },
        { x: 39, y: 11, prop: { name: "city", part: 2 } },
        { x: 39, y: 12, prop: { name: "city", part: 1 } },
        { x: 41, y: 11, prop: { name: "city", part: 4 } },
        { x: 41, y: 12, prop: { name: "city", part: 5 } },
        { x: 38, y: 12, prop: { name: "city", part: 7 } },
        { x: 42, y: 12, prop: { name: "city", part: 5 } },

        { x: 34, y: 14, prop: { name: "bridge", part: 0 } },

        // trees around Riverfall
        { x: 28, y: 16, prop: { name: "tree_oak", part: 0 } },
        { x: 35, y: 16, prop: { name: "tree_oak", part: 0 } },
        { x: 38, y: 218, prop: { name: "tree_oak", part: 0 } },
        { x: 35, y: 20, prop: { name: "tree_oak", part: 0 } },
        { x: 41, y: 21, prop: { name: "tree_oak", part: 0 } },
        { x: 49, y: 20, prop: { name: "tree_oak", part: 0 } },
        { x: 38, y: 17, prop: { name: "tree_birch", part: 0 } },
        { x: 39, y: 9, prop: { name: "tree_birch", part: 0 } },
        { x: 40, y: 14, prop: { name: "tree_birch", part: 0 } },
        { x: 42, y: 10, prop: { name: "tree_birch", part: 0 } },
        { x: 43, y: 13, prop: { name: "tree_birch", part: 0 } },
        { x: 45, y: 8, prop: { name: "tree_birch", part: 0 } },
        { x: 47, y: 11, prop: { name: "tree_birch", part: 0 } },
        { x: 48, y: 17, prop: { name: "tree_birch", part: 0 } },
        { x: 50, y: 4, prop: { name: "tree_birch", part: 0 } },
        { x: 52, y: 6, prop: { name: "tree_birch", part: 0 } },
        { x: 55, y: 9, prop: { name: "tree_birch", part: 0 } },
        { x: 49, y: 9, prop: { name: "tree_sakura", part: 0 } },
        { x: 38, y: 14, prop: { name: "tree_sakura", part: 0 } },
        { x: 41, y: 6, prop: { name: "tree_sakura", part: 0 } },
        { x: 35, y: 9, prop: { name: "tree_sakura", part: 0 } },
        { x: 47, y: 5, prop: { name: "tree_sakura", part: 0 } },
        { x: 46, y: 10, prop: { name: "tree_sakura", part: 0 } },
      ],
    },

    {
      id: "Settlement_Southbay",
      category: "Settlement",
      metadata: { name: "Southbay" },
      cells: [
        { x: 22, y: 24, prop: { name: "city", part: 0 } },
        { x: 22, y: 25, prop: { name: "city", part: 3 } },
        { x: 21, y: 24, prop: { name: "city", part: 2 } },
        { x: 21, y: 25, prop: { name: "city", part: 1 } },
        { x: 23, y: 24, prop: { name: "city", part: 4 } },
        { x: 23, y: 25, prop: { name: "city", part: 5 } },

        { x: 22, y: 22, prop: { name: "bridge", part: 1 } },

        // trees south of the city
        { x: 15, y: 28, prop: { name: "tree_palm", part: 0 } },
        { x: 15, y: 29, prop: { name: "tree_palm", part: 0 } },
        { x: 16, y: 27, prop: { name: "tree_palm", part: 0 } },
        { x: 16, y: 28, prop: { name: "tree_palm", part: 2 } },
        { x: 16, y: 29, prop: { name: "tree_palm", part: 0 } },
        { x: 16, y: 30, prop: { name: "tree_palm", part: 0 } },
        { x: 17, y: 27, prop: { name: "tree_palm", part: 0 } },
        { x: 17, y: 28, prop: { name: "tree_palm", part: 0 } },
        { x: 17, y: 29, prop: { name: "tree_palm", part: 0 } },
        { x: 17, y: 30, prop: { name: "tree_palm", part: 0 } },
        { x: 17, y: 31, prop: { name: "tree_palm", part: 2 } },
        { x: 18, y: 28, prop: { name: "tree_palm", part: 0 } },
        { x: 18, y: 29, prop: { name: "tree_palm", part: 0 } },
        { x: 18, y: 30, prop: { name: "tree_palm", part: 0 } },
        { x: 19, y: 27, prop: { name: "tree_palm", part: 0 } },
        { x: 19, y: 28, prop: { name: "tree_palm", part: 0 } },
        { x: 19, y: 29, prop: { name: "tree_palm", part: 0 } },
        { x: 19, y: 30, prop: { name: "tree_palm", part: 0 } },
        { x: 19, y: 31, prop: { name: "tree_palm", part: 0 } },
        { x: 20, y: 27, prop: { name: "tree_palm", part: 0 } },
        { x: 20, y: 28, prop: { name: "tree_palm", part: 0 } },
        { x: 20, y: 30, prop: { name: "tree_palm", part: 0 } },
        { x: 20, y: 31, prop: { name: "tree_palm", part: 0 } },
        { x: 21, y: 27, prop: { name: "tree_palm", part: 1 } },
        { x: 21, y: 29, prop: { name: "tree_palm", part: 0 } },
        { x: 21, y: 31, prop: { name: "tree_palm", part: 0 } },
        { x: 22, y: 27, prop: { name: "tree_palm", part: 0 } },
        { x: 22, y: 28, prop: { name: "tree_palm", part: 0 } },
        { x: 22, y: 29, prop: { name: "tree_palm", part: 1 } },
        { x: 22, y: 30, prop: { name: "tree_palm", part: 2 } },
        { x: 22, y: 31, prop: { name: "tree_palm", part: 0 } },
        { x: 23, y: 27, prop: { name: "tree_palm", part: 1 } },
        { x: 23, y: 28, prop: { name: "tree_palm", part: 0 } },
        { x: 23, y: 30, prop: { name: "tree_palm", part: 0 } },
        { x: 23, y: 31, prop: { name: "tree_palm", part: 0 } },
        { x: 24, y: 28, prop: { name: "tree_palm", part: 0 } },
        { x: 24, y: 29, prop: { name: "tree_palm", part: 0 } },
        { x: 24, y: 30, prop: { name: "tree_palm", part: 0 } },
        { x: 25, y: 29, prop: { name: "tree_palm", part: 0 } },
        { x: 25, y: 30, prop: { name: "tree_palm", part: 1 } },
        { x: 25, y: 31, prop: { name: "tree_palm", part: 2 } },
        { x: 26, y: 26, prop: { name: "tree_palm", part: 0 } },
        { x: 26, y: 27, prop: { name: "tree_palm", part: 0 } },
        { x: 26, y: 29, prop: { name: "tree_palm", part: 0 } },
        { x: 26, y: 30, prop: { name: "tree_palm", part: 0 } },
        { x: 26, y: 31, prop: { name: "tree_palm", part: 0 } },
        { x: 27, y: 26, prop: { name: "tree_palm", part: 0 } },
        { x: 27, y: 27, prop: { name: "tree_palm", part: 0 } },
        { x: 27, y: 28, prop: { name: "tree_palm", part: 0 } },
        { x: 27, y: 29, prop: { name: "tree_palm", part: 0 } },
        { x: 27, y: 30, prop: { name: "tree_palm", part: 0 } },
        { x: 27, y: 31, prop: { name: "tree_palm", part: 0 } },
        { x: 28, y: 27, prop: { name: "tree_palm", part: 0 } },
        { x: 28, y: 28, prop: { name: "tree_palm", part: 0 } },
        { x: 28, y: 29, prop: { name: "tree_palm", part: 0 } },
        { x: 28, y: 30, prop: { name: "tree_palm", part: 2 } },
        { x: 29, y: 28, prop: { name: "tree_palm", part: 2 } },
        { x: 29, y: 29, prop: { name: "tree_palm", part: 1 } },
        { x: 19, y: 23, prop: { name: "tree_palm", part: 2 } },
        { x: 20, y: 23, prop: { name: "tree_palm", part: 0 } },
        { x: 19, y: 24, prop: { name: "tree_palm", part: 0 } },
        { x: 24, y: 23, prop: { name: "tree_palm", part: 0 } },
        { x: 25, y: 23, prop: { name: "tree_palm", part: 0 } },
        { x: 25, y: 24, prop: { name: "tree_palm", part: 1 } },
      ],
    },
  ],
};

export const mockWorld: World = Mapper.mapToWorld(mockWorldDto);

for (const { x, y, type } of TILE_OVERRIDES) {
  const tile = tiles.find(t => t.x === x && t.y === y);
  if (tile) {
    tile.type = type;
  }
}

mockWorld.tiles = tiles;